//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrograAvanzadaP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrograAvanzadaEntities : DbContext
    {
        public PrograAvanzadaEntities()
            : base("name=PrograAvanzadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Imagenes_x_Recetas> Imagenes_x_Recetas { get; set; }
        public virtual DbSet<ListaEstudiante> ListaEstudiantes { get; set; }
        public virtual DbSet<ListaReceta> ListaRecetas { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<VistaCursosActivo> VistaCursosActivos { get; set; }
        public virtual DbSet<VistaCursosEstudianteConIdUsuario> VistaCursosEstudianteConIdUsuarios { get; set; }
    
        [DbFunction("PrograAvanzadaEntities", "CursosEstudiante")]
        public virtual IQueryable<CursosEstudiante_Result> CursosEstudiante(string idEstudiante)
        {
            var idEstudianteParameter = idEstudiante != null ?
                new ObjectParameter("IdEstudiante", idEstudiante) :
                new ObjectParameter("IdEstudiante", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CursosEstudiante_Result>("[PrograAvanzadaEntities].[CursosEstudiante](@IdEstudiante)", idEstudianteParameter);
        }
    }
}
